### ISSUE TITLE
Fails to upload new class

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-frontend#115]
```
2018-10-09 10:32:51   run osmosis all analyser SubAnalyser_Merge_Healthcare_FR_Finess_200
2018-10-09 10:32:51   Analyser_Merge.py:846 sql
2018-10-09 10:32:51   Analyser_Merge.py:608 sql
2018-10-09 10:32:52   Convert data to tags
2018-10-09 10:32:52   Analyser_Merge.py:648 sql
2018-10-09 10:32:52   Analyser_Merge.py:649 sql
2018-10-09 10:32:52   Analyser_Merge.py:695 sql
2018-10-09 10:32:52   Analyser_Merge.py:700 sql
2018-10-09 10:32:52   Empty bbox, abort
2018-10-09 10:32:52   update
2018-10-09 10:32:52     iteration=1
UPDATE ERROR france_local_db/merge_healthcare_FR_finess : Traceback (most recent call last):
  File "/data/project/osmose/frontend/control.py", line 275, in send_update
    tools.update.update(source_id, save_filename, remote_ip=remote_ip)
  File "/data/project/osmose/frontend/tools/update.py", line 83, in update
    parser.parse(f)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 320, in end_element
    self._cont_handler.endElement(name)
  File "/data/project/osmose/frontend/tools/update.py", line 352, in endElement
    execute_sql(self._dbcurs, sql, vals)
  File "/data/project/osmose/frontend/tools/update.py", line 53, in execute_sql
    dbcurs.execute(sql, args)
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/psycopg2/extras.py", line 144, in execute
    return super(DictCursor, self).execute(query, vars)
IntegrityError: insert or update on table "dynpoi_class" violates foreign key constraint "class_item_class_fkey"
DETAIL:  Key (item, class)=(8330, 11) is not present in table "class".
```

**Comment by jocelynj** [comment]
Should table class be automatically updated on update, like for dynpoi_class ?

**Comment by frodrigo** [comment]
Yes
