### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by matthewdarwin** [osm-fr/osmose-frontend#153]
http://osmose.openstreetmap.fr/en/error/30223781310

Error: 500 Internal Server Error

Sorry, the requested URL 'http://osmose.openstreetmap.fr/en/error/30223781310' caused an error:

Internal Server Error

**Comment by frodrigo** [comment]
```
[Tue Jul 30 15:45:12.828320 2019]Traceback (most recent call last):
[Tue Jul 30 15:45:12.828361 2019]  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/bottle.py", line 862, in _handle
[Tue Jul 30 15:45:12.828366 2019]    return route.call(**args)
[Tue Jul 30 15:45:12.828370 2019]  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
[Tue Jul 30 15:45:12.828375 2019]    rv = callback(*a, **ka)
[Tue Jul 30 15:45:12.828379 2019]  File "/data/project/osmose/frontend/bottle_pgsql.py", line 107, in wrapper
[Tue Jul 30 15:45:12.828383 2019]    rv = callback(*args, **kwargs)
[Tue Jul 30 15:45:12.828387 2019]  File "/data/project/osmose/frontend/bottle_cors.py", line 32, in wrapper
[Tue Jul 30 15:45:12.828391 2019]    return callback(*args, **kwargs)
[Tue Jul 30 15:45:12.828395 2019]  File "/data/project/osmose/frontend/bottle_gettext.py", line 99, in wrapper
[Tue Jul 30 15:45:12.828399 2019]    return callback(*args, **kwargs)
[Tue Jul 30 15:45:12.828403 2019]  File "/data/project/osmose/frontend/bottle_user.py", line 46, in wrapper
[Tue Jul 30 15:45:12.828407 2019]    return callback(*args, **kwargs)
[Tue Jul 30 15:45:12.828411 2019]  File "/data/project/osmose/frontend/error.py", line 118, in display
[Tue Jul 30 15:45:12.828416 2019]    fix=fix, columns_fix=columns_fix, main_website=utils.main_website, data_type=data_type)
[Tue Jul 30 15:45:12.828420 2019]  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/bottle.py", line 3619, in template
[Tue Jul 30 15:45:12.828424 2019]    return TEMPLATES[tplid].render(kwargs)
[Tue Jul 30 15:45:12.828428 2019]  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/bottle.py", line 3409, in render
[Tue Jul 30 15:45:12.828433 2019]    self.execute(stdout, env)
[Tue Jul 30 15:45:12.828437 2019]  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/bottle.py", line 3396, in execute
[Tue Jul 30 15:45:12.828441 2019]    eval(self.co, env)
[Tue Jul 30 15:45:12.828445 2019]  File "/data/project/osmose/frontend/views/error/index.tpl", line 112, in <module>
[Tue Jul 30 15:45:12.828449 2019]    %    show_html_results(columns_fix, i)
[Tue Jul 30 15:45:12.828453 2019]  File "/data/project/osmose/frontend/views/error/index.tpl", line 48, in show_html_results
[Tue Jul 30 15:45:12.828457 2019]    %            show_html_tags(res[i])
[Tue Jul 30 15:45:12.828466 2019]  File "/data/project/osmose/frontend/views/error/index.tpl", line 12, in show_html_tags
[Tue Jul 30 15:45:12.828470 2019]    <tr><td>{{kv['k']}}</td><td>{{kv['v']}}</td><td><a href="{{kv.get('vlink', '')}}">{{kv.get('vlink', '')}}</a></td></tr>
```

**Comment by frodrigo** [comment]
Done.
