### ISSUE TITLE
14 vs 12 parameters for errors_graph.py

### ISSUE THREAD

**Issue by didier2020** [osm-fr/osmose-frontend#190]
hello,
this error since last update :

Traceback (most recent call last):
  File "/data/project/osmose/frontend/errors.py", line 134, in graph
    data = errors_graph.make_plt(db, options, format)
  File "/data/project/osmose/frontend/errors_graph.py", line 129, in make_plt

    data = get_data(db, options)
  File "/data/project/osmose/frontend/errors_graph.py", line 72, in get_data
    join, where = query._build_param(None, params.source, params.item, params.level, None, params.classs, params.country, params.useDevItem, None, params.tags, None, stats=True, start_date=params.start_date, end_date=params.end_date)
TypeError: _build_param() takes at least 12 arguments (14 given)

**Comment by jocelynj** [comment]
Linked to #188

**Comment by frodrigo** [comment]
Not linked to #188

**Comment by frodrigo** [comment]
Fixed. Thank you for report.
