### ISSUE TITLE
del data["tag"][k] KeyError: u'diaper'

### ISSUE THREAD

**Issue by frodrigo** [osm-fr/osmose-frontend#192]
```
{u'changeset': u'72045784', u'uid': u'1624486', u'timestamp': u'2019-07-09T09:23:55Z', u'lon': 9.3770223, u'visible': u'true', u'version': 2, u'user': u'thetornado76', u'lat': 39.5210169, u'tag': {u'cuisine': u'italian', u'amenity': u'restaurant', u'name': u'Locanda I 4 venti', u'toilets': u'yes', u'opening_hours': u'Tu-Su 12:00-14:00; Tu-Su 19:00-22:30', u'wheelchair': u'limited', u'outdoor_seating': u'yes', u'toilets:access': u'customers', u'changing_table': u'yes', u'toilets:wheelchair': u'designated'}, u'id': 5986763748}
Traceback (most recent call last):
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/data/project/osmose/frontend/bottle_pgsql.py", line 108, in wrapper
    rv = callback(*args, **kwargs)
  File "/data/project/osmose/frontend/bottle_cors.py", line 32, in wrapper
    return callback(*args, **kwargs)
  File "/data/project/osmose/frontend/error.py", line 323, in fix_uuid
    return _fix(3, db, uuid, fix_num, _get_fix(db, fix_num, uuid=uuid))
  File "/data/project/osmose/frontend/error.py", line 337, in _fix
    osm_read.CopyTo(o)
  File "/data/project/osmose/frontend/tools/OsmSax.py", line 87, in CopyTo
    parser.parse(self._GetFile())
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 320, in end_element
    self._cont_handler.endElement(name)
  File "/data/project/osmose/frontend/tools/OsmSax.py", line 143, in endElement
    self._output.NodeCreate(self._data)
  File "/data/project/osmose/frontend/error.py", line 396, in NodeCreate
    data = self.fix_tags(data)
  File "/data/project/osmose/frontend/error.py", line 386, in fix_tags
    del data["tag"][k]
KeyError: u'diaper'
```

The fix try to remove an already deleted tags:
- [x] This should not raise an error
- [ ] The tag was deleted long ago, the extract is not up to date, cc @jocelynj 

http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=39.521097&lon=9.37635&item=xxxx&level=1%2C2%2C3&tags=&fixable=
https://www.openstreetmap.org/node/5986763748/history#map=17/39.52045/9.37661

**Comment by jocelynj** [comment]
i've just checked the extract for sardegna, and it contains version 2 of the object, which is correct as version 3 is less than 21 hours:
```
        <node id="5986763748" lat="39.5210169" lon="9.3770223" version="2" timestamp="2019-07-09T09:23:55Z" changeset="72045784" uid="1624486" user="thetornado76">
                <tag k="cuisine" v="italian"/>
                <tag k="amenity" v="restaurant"/>
                <tag k="name" v="Locanda I 4 venti"/>
                <tag k="toilets" v="yes"/>
                <tag k="opening_hours" v="Tu-Su 12:00-14:00; Tu-Su 19:00-22:30"/>
                <tag k="wheelchair" v="limited"/>
                <tag k="outdoor_seating" v="yes"/>
                <tag k="toilets:access" v="customers"/>
                <tag k="changing_table" v="yes"/>
                <tag k="toilets:wheelchair" v="designated"/>
        </node>
```

I will check the extracts on the last osmose backend which ran this country.

**Comment by jocelynj** [comment]
I will remove all extracts from osmose backend to start from a fresh state.
