### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-frontend#360]
On http://osmose.openstreetmap.fr/nl/issues/graph.png?country=iraq (or any random country)
```
Traceback (most recent call last):
  File "/data/project/osmose/frontend/web_api/issues.py", line 44, in graph
    data = errors_graph.make_plt(db, Params(), format)
  File "/data/project/osmose/frontend/web_api/errors_graph.py", line 150, in make_plt
    text = get_text(db, params)
  File "/data/project/osmose/frontend/web_api/errors_graph.py", line 94, in get_text
    elif len(params.item)==1 and len(params.classs)==1:
TypeError: object of type 'NoneType' has no len()
```

How to reach?
1. From the issues list (e.g. http://osmose.openstreetmap.fr/nl/issues/open?item=1040 if you clicked on item 1040 in the front page)
2. Click on one of the country _names_ (I randomly chose Iraq in this example, bringing me to http://osmose.openstreetmap.fr/nl/issues/open?country=iraq )
3. Click `graph` on top

**Comment by frodrigo** [comment]
Fixed on last version.
