### ISSUE TITLE
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "items"

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-frontend#414]
Visit https://osmose.openstreetmap.fr/nl/issues/graph.png?item=9020&useDevItem=true
```
Traceback (most recent call last):
  File "/data/project/osmose/frontend/web_api/issues.py", line 38, in graph
    data = errors_graph.make_plt(db, Params(), format)
  File "/data/project/osmose/frontend/web_api/errors_graph.py", line 149, in make_plt
    data = get_data(db, params)
  File "/data/project/osmose/frontend/web_api/errors_graph.py", line 85, in get_data
    db.execute(sql)
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/psycopg2/extras.py", line 146, in execute
    return super().execute(query, vars)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "items"
LINE 24:         items.item IS NULL
                 ^
```

**Comment by frodrigo** [comment]
Since we removed psycopg2 the error message changed, but the issue is the same.

**Comment by frodrigo** [comment]
Fixed.
