### ISSUE TITLE
Dragging map occasionally stops working

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-frontend#433]
Not really found a pattern in it, but occasionally when opening 'balloons', zooming in and out and dragging the map around, the dragging stops working and you'll get the following in the console:
```
Uncaught (in promise) TypeError: L.Path.prototype._createElement is not a function
    at e.setText (webpack.bundle-f2c1c47cb268add1268e.js:2:97060)
    at e._textRedraw (webpack.bundle-f2c1c47cb268add1268e.js:2:96588)
    at e.onAdd (webpack.bundle-f2c1c47cb268add1268e.js:2:96267)
    at e._layerAdd (webpack.bundle-f2c1c47cb268add1268e.js:2:199660)
    at e.whenReady (webpack.bundle-f2c1c47cb268add1268e.js:2:194821)
    at e.addLayer (webpack.bundle-f2c1c47cb268add1268e.js:2:199973)
    at e.onAdd (webpack.bundle-f2c1c47cb268add1268e.js:2:241676)
    at e._layerAdd (webpack.bundle-f2c1c47cb268add1268e.js:2:199660)
    at e.whenReady (webpack.bundle-f2c1c47cb268add1268e.js:2:194821)
    at e.addLayer (webpack.bundle-f2c1c47cb268add1268e.js:2:199973)
```
which when expanded in Chrome, also shows this:
```
setText	@	webpack.bundle-f2c1c47….js:2
_textRedraw	@	webpack.bundle-f2c1c47….js:2
_updatePath	@	webpack.bundle-f2c1c47….js:2
_update	@	webpack.bundle-f2c1c47….js:2
_reset	@	webpack.bundle-f2c1c47….js:2
onAdd	@	webpack.bundle-f2c1c47….js:2
onAdd	@	webpack.bundle-f2c1c47….js:2
_layerAdd	@	webpack.bundle-f2c1c47….js:2
whenReady	@	webpack.bundle-f2c1c47….js:2
addLayer	@	webpack.bundle-f2c1c47….js:2
onAdd	@	webpack.bundle-f2c1c47….js:2
_layerAdd	@	webpack.bundle-f2c1c47….js:2
whenReady	@	webpack.bundle-f2c1c47….js:2
addLayer	@	webpack.bundle-f2c1c47….js:2
addLayer	@	webpack.bundle-f2c1c47….js:2
(anonymous)	@	webpack.bundle-8a3448d….js:1
Promise.then (async)		
(anonymous)	@	webpack.bundle-8a3448d….js:1
_setPopup	@	webpack.bundle-8a3448d….js:1
(anonymous)	@	webpack.bundle-8a3448d….js:1
(anonymous)	@	webpack.bundle-afcb4bb….js:2
xr	@	webpack.bundle-afcb4bb….js:2
Promise.then (async)		
gr	@	webpack.bundle-afcb4bb….js:2
Sr	@	webpack.bundle-afcb4bb….js:2
tr	@	webpack.bundle-afcb4bb….js:2
t.update	@	webpack.bundle-afcb4bb….js:2
t.notify	@	webpack.bundle-afcb4bb….js:2
set	@	webpack.bundle-afcb4bb….js:2
Wr.set	@	webpack.bundle-afcb4bb….js:2
(anonymous)	@	webpack.bundle-8a3448d….js:1
Promise.then (async)		
load	@	webpack.bundle-8a3448d….js:1
pr	@	webpack.bundle-afcb4bb….js:2
t.$emit	@	webpack.bundle-afcb4bb….js:2
(anonymous)	@	webpack.bundle-8a3448d….js:1
setTimeout (async)		
_openPopup	@	webpack.bundle-8a3448d….js:1
n	@	webpack.bundle-8a3448d….js:1
fire	@	webpack.bundle-f2c1c47….js:2
_propagateEvent	@	webpack.bundle-f2c1c47….js:2
fire	@	webpack.bundle-f2c1c47….js:2
_fireDOMEvent	@	webpack.bundle-f2c1c47….js:2
_handleDOMEvent	@	webpack.bundle-f2c1c47….js:2
s	@	webpack.bundle-f2c1c47….js:2
```
(I do realize this is a compressed javascript file, so the stack trace is probably not exactly useful)

**Comment by vinber** [comment]
same problem sometime !

![image](https://user-images.githubusercontent.com/890869/223665537-8f414ce1-f74d-4dca-97be-c6e48dc769a2.png)

**Comment by frodrigo** [comment]
Done with the switch to MapLibre.
