### ISSUE TITLE
TypeError: an integer is required (got type list)

### ISSUE THREAD

**Issue by Famlam** [osm-fr/osmose-frontend#435]
https://osmose.openstreetmap.fr/nl/issues/graph.png?source=5754&item=3150&class=1

```
Traceback (most recent call last):
  File "asyncpg/protocol/prepared_stmt.pyx", line 168, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
  File "asyncpg/protocol/codecs/base.pyx", line 206, in asyncpg.protocol.protocol.Codec.encode
  File "asyncpg/protocol/codecs/base.pyx", line 111, in asyncpg.protocol.protocol.Codec.encode_scalar
  File "asyncpg/pgproto/./codecs/int.pyx", line 54, in asyncpg.pgproto.pgproto.int4_encode
TypeError: an integer is required (got type list)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/project/osmose/frontend/web_api/issues.py", line 30, in graph
    data = await errors_graph.make_plt(db, params, format)
  File "/data/project/osmose/frontend/web_api/errors_graph.py", line 201, in make_plt
    text = await get_text(db, params)
  File "/data/project/osmose/frontend/web_api/errors_graph.py", line 104, in get_text
    return await db.fetchval(
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/asyncpg/connection.py", line 644, in fetchval
    data = await self._execute(query, args, 1, timeout)
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/asyncpg/connection.py", line 1658, in _execute
    result, _ = await self.__execute(
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/asyncpg/connection.py", line 1683, in __execute
    return await self._do_execute(
  File "/data/project/osmose/frontend/osmose-frontend-venv/lib/python3.9/site-packages/asyncpg/connection.py", line 1730, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 183, in bind_execute
  File "asyncpg/protocol/prepared_stmt.pyx", line 197, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
asyncpg.exceptions.DataError: invalid input for query argument $1: [5754] (an integer is required (got type list))

```

**Comment by frodrigo** [comment]
Fixed
