### ISSUE TITLE
docker build failure

### ISSUE THREAD

**Issue by Marc-marc-marc** [osm-fr/osmose-frontend#459]
$ docker-compose build
postgres uses an image, skipping
Building api
Step 1/11 : FROM python:3.8
 ---> 3574362edbef
Traceback (most recent call last):
  File "/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.18.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 124, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.6/site-packages/compose/cli/main.py", line 254, in build
    build_args=build_args)
  File "/usr/lib/python3.6/site-packages/compose/project.py", line 364, in build
    service.build(no_cache, pull, force_rm, memory, build_args)
  File "/usr/lib/python3.6/site-packages/compose/service.py", line 972, in build
    all_events = stream_output(build_output, sys.stdout)
  File "/usr/lib/python3.6/site-packages/compose/progress_stream.py", line 23, in stream_output
    print_output_event(event, stream, is_terminal)
  File "/usr/lib/python3.6/site-packages/compose/progress_stream.py", line 90, in print_output_event
    stream.write("%s%s" % (event['stream'], terminator))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 25: ordinal not in range(128)

**Comment by frodrigo** [comment]
I rebuild it yesterday without this issue.
I update the python version to 3.11.

But there is some thing strange in your log, the python image is in 3.8, but on the logs I see 3.6.
